# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 311814ddada84cc3876e5711956b7549fab977470ed668691b5368f7e36bb38acb401faa25979af1e4f222817f249532c30c4a04ac97b952e128cc9de176dc72

test:
  secret_key_base: 3d3673adb51962caf430bfaec46cb924134e9c15c3871dd8c8a9328db64baf23f5fe797ce6c6470be48d318529002616fad540f96781473248da415d79349d4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
